//
// Created by danis on 06/01/2021.
//

#ifndef ENDLESSRUNNER_CONSTANTS_H
#define ENDLESSRUNNER_CONSTANTS_H
#define SCREENWIDTH  1280
#define SCREENHEIGHT  720
#define INIT_SPEEDB 0.3
#define INIT_SPEEDL 0.8
#define LHEIGHT (SCREENHEIGHT-SCREENHEIGHT/6)
#endif //ENDLESSRUNNER_CONSTANTS_H
