//
// Created by danis on 06/01/2021.
//

#ifndef ENDLESSRUNNER_CONSTANTS_H
#define ENDLESSRUNNER_CONSTANTS_H
#define SCREENWIDTH  1280
#define SCREENHEIGHT  720
#define INIT_SPEEDB 1.5
#define INIT_SPEEDL 2.8f
#define LHEIGHT (SCREENHEIGHT-SCREENHEIGHT/6)
#define MAXJUMP  300
#endif //ENDLESSRUNNER_CONSTANTS_H
